import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[shell]
program = "/run/current-system/sw/bin/zsh"
args = ["--login"]

[env]
TERM = "xterm-256color"

[font]
size = 7.0

[font.bold]
family = "MesloLGS Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font"
style = "Regular"
